openapi: 3.0.0
info:
  title: Runbook API
  version: 1.0.0
  description: API documentation for Runbook service
servers:
  - url: http://localhost:3000/runbook/api/v1
    description: Local Server
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the server
      tags:
        - Health
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: OK